admin/base/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.views.generic import RedirectView

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
    url(base_pattern,
        include(patterns('',
                         url(r'^$', views.home, name='home'),
                         url(r'^django_admin/', include(admin.site.urls)),
                         url(r'^spam/', include('admin.spam.urls', namespace='spam')),
                         url(r'^auth/', include('admin.common_auth.urls', namespace='auth')),
                         url(r'^nodes/',
                             include('admin.nodes.urls', namespace='nodes')),
                         url(r'^users/',
                             include('admin.users.urls', namespace='users')),
                         url(r'^prereg/', include('admin.pre_reg.urls', namespace='pre_reg')),
                         url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                            views.password_reset_confirm_custom, name='password_reset_confirm'),
                         url(r'^reset/done/$', views.password_reset_done,
                            name='password_reset_complete'),
                         )
                )
        ),
    url(r'^$', RedirectView.as_view(url='/admin/')),
]

admin/pre_reg/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.prereg, name='prereg'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/$', views.view_draft, name='view_draft'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/update/$', views.update_draft, name='update_draft'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/approve/$', views.approve_draft, name='approve_draft'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/reject/$', views.reject_draft, name='reject_draft'),
    url(r'^(?P<node_id>[a-zA-Z0-9]{5})/files/(?P<provider>.+?)/(?P<file_id>.+)/?', views.view_file, name='view_file')
]

api/base/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from settings import API_BASE
from website import settings as osf_settings

from . import views

base_pattern = '^{}'.format(API_BASE)

urlpatterns = [
    url(base_pattern,
        include(patterns('',
                         url(r'^$', views.root, name='root'),
                         url(r'^applications/', include('api.applications.urls', namespace='applications')),
                         url(r'^comments/', include('api.comments.urls', namespace='comments')),
                         url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                         url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                         url(r'^users/', include('api.users.urls', namespace='users')),
                         url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                         url(r'^logs/', include('api.logs.urls', namespace='logs')),
                         url(r'^files/', include('api.files.urls', namespace='files')),
                         url(r'^docs/', include('rest_framework_swagger.urls')),
                         url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                         ))
        )
]

if osf_settings.DEV_MODE:
    urlpatterns.extend([
        url(r'^v2/collections/', include('api.collections.urls', namespace='collections')),
    ])

urlpatterns += static('/static/', document_root=settings.STATIC_ROOT)

handler404 = views.error_404

admin/pre_reg/forms.py
import itertools

from django import forms

from admin.pre_reg.utils import get_prereg_reviewers


class DraftRegistrationForm(forms.Form):

    proof_of_publication = forms.ChoiceField(
        label="Proof of publication",
        choices=(
            ("not_submitted", "Published Article Not Yet Submitted"),
            ("submitted", "Published Article Submitted"),
            ("under_review", "Published Article Under Review"),
            ("approved", "Published Article Approved"),
            ("rejected", "Published Article Rejected"),
        )
    )
    payment_sent = forms.BooleanField(
        label="Payment sent",
        required=False
    )
    assignee = forms.ChoiceField(
        label="Assignee",
        choices=list(),
        required=False,
    )

    notes = forms.CharField(
        label="Notes",
        widget=forms.Textarea(
            attrs={
                'class': 'prereg-form-notes'
            }
        ),
        required=False
    )

    def __init__(self, *args, **kwargs):
        prereg_reviewers = itertools.chain(
            ((None, 'None'), ), get_prereg_reviewers())
        self.base_fields['assignee'] = forms.ChoiceField(
            choices=prereg_reviewers)
        super(DraftRegistrationForm, self).__init__(*args, **kwargs)

admin/pre_reg/views.py
import functools
import httplib as http
import json
import operator
from copy import deepcopy

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import HttpResponseBadRequest
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from admin.pre_reg import serializers
from admin.pre_reg.forms import DraftRegistrationForm
from framework.exceptions import HTTPError
from framework.mongo.utils import get_or_http_error
from modularodm import Q
from website.exceptions import NodeStateError
from website.files.models import FileNode
from website.project.model import MetaSchema, DraftRegistration

get_draft_or_error = functools.partial(get_or_http_error, DraftRegistration)


def get_prereg_drafts(user=None, filters=tuple()):
    prereg_schema = MetaSchema.find_one(
        Q('name', 'eq', 'Prereg Challenge') &
        Q('schema_version', 'eq', 2)
    )
    query = (
        Q('registration_schema', 'eq', prereg_schema) &
        Q('approval', 'ne', None)
    )
    if user:
        pass
        # TODO: filter by assignee; this requires multiple levels of Prereg admins-
        # one level that can see all drafts, and another than can see only the ones they're assigned.
        # As a followup to this, we need to make sure this applies to approval/rejection/commenting endpoints
        # query = query & Q('_metaschema_flags.assignee', 'eq', user._id)
    return sorted(
        DraftRegistration.find(query),
        key=operator.attrgetter('approval.initiation_date')
    )


def is_in_prereg_group(user):
    """Determines whether a user is in the prereg_group
    :param user: User wanting access to prereg material
    :return: True if prereg False if not
    """
    return user.is_in_group('prereg_group')


@login_required
@user_passes_test(is_in_prereg_group)
def prereg(request):
    """Redirects to prereg page if user has prereg access
    :param request: Current logged in user
    :return: Redirect to prereg page with username, reviewers, and user obj
    """
    paginator = Paginator(get_prereg_drafts(user=request.user), 5)

    try:
        page_number = int(request.GET.get('page'))
    except (TypeError, ValueError):
        page_number = 1

    page = paginator.page(page_number)

    try:
        drafts = [serializers.serialize_draft_registration(d, json_safe=False) for d in page]
    except EmptyPage:
        drafts = []

    for draft in drafts:
        draft['form'] = DraftRegistrationForm(draft)

    context = {
        'drafts': drafts,
        'page': page,
        'IMMEDIATE': serializers.IMMEDIATE,
    }
    return render(request, 'pre_reg/prereg.html', context)


@login_required
@user_passes_test(is_in_prereg_group)
def view_draft(request, draft_pk):
    """Redirects to prereg form review page if user has prereg access
    :param draft_pk: Unique id for selected draft
    :return: Redirect to prereg form review page with draft obj
    """
    draft = get_draft_or_error(draft_pk)
    context = {
        'draft': serializers.serialize_draft_registration(draft)
    }
    return render(request, 'pre_reg/edit_draft_registration.html', context)

@login_required
@user_passes_test(is_in_prereg_group)
def view_file(request, node_id, provider, file_id):
    file = FileNode.load(file_id)
    wb_url = file.generate_waterbutler_url()
    return redirect(wb_url)

@csrf_exempt
@login_required
@user_passes_test(is_in_prereg_group)
def approve_draft(request, draft_pk):
    """Approves current draft
    :param request: mostly for user
    :param draft_pk: Unique id for current draft
    :return: DraftRegistrationApproval obj
    """
    draft = get_draft_or_error(draft_pk)

    user = request.user.osf_user
    draft.approve(user)
    return redirect(reverse('pre_reg:prereg') + "?page={0}".format(request.POST.get('page', 1)), permanent=True)


@csrf_exempt
@login_required
@user_passes_test(is_in_prereg_group)
def reject_draft(request, draft_pk):
    """Rejects current draft
    :param request: mostly for user
    :param draft_pk: Unique id for current draft
    :return: DraftRegistrationApproval obj
    """
    draft = get_draft_or_error(draft_pk)

    user = request.user.osf_user
    draft.reject(user)
    return redirect(reverse('pre_reg:prereg') + "?page={0}".format(request.POST.get('page', 1)), permanent=True)


@csrf_exempt
@login_required
def update_draft(request, draft_pk):
    """Updates current draft to save admin comments

    :param draft_pk: Unique id for current draft
    :return: DraftRegistration obj
    """
    data = json.loads(request.body)
    draft = get_draft_or_error(draft_pk)

    if 'admin_settings' in data:
        form = DraftRegistrationForm(data=data['admin_settings'])
        if not form.is_valid():
            return HttpResponseBadRequest("Invalid form data")
        admin_settings = form.cleaned_data
        draft.notes = admin_settings.get('notes', draft.notes)
        del admin_settings['notes']
        draft.flags = admin_settings
        draft.save()
    else:
        schema_data = data.get('schema_data', {})
        data = deepcopy(draft.registration_metadata)
        for key, value in data.items():
            data[key]['comments'] = schema_data.get(key, {}).get('comments', [])
        try:
            draft.update_metadata(data)
            draft.save()
        except (NodeStateError):
            raise HTTPError(http.BAD_REQUEST)
    return JsonResponse(serializers.serialize_draft_registration(draft))

website/prereg/views.py
"""Back-end code to support the Prereg Challenge initiative

Keeping the code together in this file should make it easier to remove the
features added to the OSF specifically to support this initiative in the future.

Other resources that are a part of the Prereg Challenge:

* website/static/js/pages/prereg-landing-page.js
* website/static/css/prereg.css
"""
from modularodm import Q

from framework.auth import decorators
from framework.utils import iso8601format
from website.util import permissions
from website.prereg.utils import get_prereg_schema

def drafts_for_user(user):
    from website import models  # noqa

    user_projects = models.Node.find(
        Q('is_deleted', 'eq', False) &
        Q('permissions.{0}'.format(user._id), 'in', [permissions.ADMIN])
    )
    PREREG_CHALLENGE_METASCHEMA = get_prereg_schema()
    return models.DraftRegistration.find(
        Q('registration_schema', 'eq', PREREG_CHALLENGE_METASCHEMA) &
        Q('approval', 'eq', None) &
        Q('registered_node', 'eq', None) &
        Q('branched_from', 'in', [p._id for p in user_projects])
    )

@decorators.must_be_logged_in
def prereg_landing_page(auth, **kwargs):
    """Landing page for the prereg challenge"""
    registerable_nodes = [
        node for node
        in auth.user.contributor_to
        if node.has_permission(user=auth.user, permission='admin')
    ]
    has_projects = bool(registerable_nodes)
    has_draft_registrations = bool(drafts_for_user(auth.user).count())

    return {
        'has_draft_registrations': has_draft_registrations,
        'has_projects': has_projects,
    }


@decorators.must_be_logged_in
def prereg_draft_registrations(auth, **kwargs):
    """API endpoint; returns prereg draft registrations the user can resume"""
    drafts = drafts_for_user(auth.user)
    return {
        'draftRegistrations': [
            {
                'dateUpdated': iso8601format(draft.datetime_updated),
                'dateInitiated': iso8601format(draft.datetime_initiated),
                'node': {
                    'title': draft.branched_from.title,
                },
                'initiator': {
                    'name': draft.initiator.fullname,
                },
                'url': draft.branched_from.web_url_for(
                    'edit_draft_registration_page',
                    draft_id=draft._id,
                ),
            }
            for draft in drafts
        ],
    }

admin/templates/pre_reg/edit_draft_registration.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}
{% load staticfiles %}
{% load filters %}

{% block title %}
<title>OSF Admin | {{ draft.title }}</title>
{% endblock %}


{% block content %}
{% render_bundle 'vendor' %}
<link href="{% static 'css/registrations.css' %}" rel="stylesheet" type="text/css" />
<script type="application/javascript">
   window.contextVars = window.contextVars || {};
   window.contextVars.currentUser = {
     id: -1,
     fullname: 'Prereg Admin'
   };
   window.contextVars.draft = {{ draft | jsonify | safe }};
   window.contextVars.urls = {
     updateDraft: '{% url 'pre_reg:update_draft' draft.pk %}'
   };
</script>

<div class="container-fluid scripted" id="draftRegistrationScope">
    <div class="row">
        <div class="col-md-9 col-sm-9">
            <h3>Review draft submission</h3>
        </div>
        <div class="col-md-3 col-sm-3">
            <h5>Last saved: <span data-bind="text: $root.lastSaved"></span></h5>
        </div>
    </div>
    <hr />
  <div class="row">
    <div class="col-md-12">
      <div id="registrationEditorScope">
        <div class="container">
          <div class="row-fluid">
            <div class="span2 col-md-2 columns eight large-8">
              <ul class="nav nav-stacked list-group" data-bind="foreach: {data: pages, as: 'page'}, visible: pages().length > 1">
                <li class="re-navbar">
                  <a class="registration-editor-page" id="top-nav" style="text-align: left;" data-bind="text: title, click: $root.selectPage.bind($root), style:{'font-weight': active() ? 'bold' : 'normal'}">
                    <i class="fa fa-caret-right"></i>
                  </a>
                </li>
              </ul>
            </div>
            <div class="span10 col-md-8 col-sm-10 columns eight large-8">
              <!-- EDITOR -->
              <div data-bind="if: currentPage">
                <div data-bind="foreach: {data: currentPage().questions, as: 'question'}">
                  <div class="row">
                    <strong data-bind="attr.id: question.id, text: question.title"></strong>:
                    <div class="well">
                      <p>
                        <span data-bind="previewQuestion: $root.context(question, $root, true)"></span>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="well col-md-10" data-bind="template: {data: currentPage, name: 'commentable'}"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="row" data-bind="ifnot: onLastPage">
        <a data-bind="click: nextPage" class="btn btn-primary">Next Page</a>
    </div>
</div>
{% include "pre_reg/registration_editor_templates.html" %}
{% endblock %}

{% block bottom_js %}
  {% render_bundle 'admin-registration-edit-page' %}
{% endblock %}

admin/templates/pre_reg/prereg.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}
{% load filters %}

{% block top_includes %}
  {% load static %}
  <link type="text/css" rel="stylesheet" href="{% static 'css/prereg.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid">
  {% for draft in drafts %}
  <div class="row osf-box osx-box-round prereg-draft" style="padding-top: 10px; padding-bottom: 10px;">
    <div class="col-md-4">
      <!-- Approval state -->
      <h4>
        {% if draft.is_pending_approval %}
        <span
           class="prereg-draft-state prereg-draft-state-pending label label-lg label-warning">Pending Approval</span>
        {% elif draft.is_approved %}
        <span
           class="prereg-draft-state prereg-draft-state-approved label label-lg label-success">Approved</span>
        {% elif draft.is_rejected %}
        <span
           class="prereg-draft-state prereg-draft-state-rejected label label-lg label-danger">Rejected</span>
        {% endif %}
      </h4>
      <!-- Info -->
      <h3> {{ draft.title }} </h3>
      <span class="text-muted"> Applicant </span> <strong> {{ draft.initiator.full_name }}</strong>
      submitted on <strong>{{ draft.submitted | date:"N dS" }}</strong> at <strong>{{draft.submitted | date:"g:i a" }}</strong>
      <br />
      <a href="mailto:{{ draft.initiator.username }}">{{ draft.initiator.username }} </a>
      <br />
      <span>Embargo release:
          {% if draft.embargo == IMMEDIATE %}
              <strong>{{ draft.embargo | capfirst }}</strong>
          {% else %}
              <strong>{{ draft.embargo | date:"N dS Y" }}</strong> at <strong>{{draft.embargo | date:"g:i a" }}</strong>
          {%  endif %}
      </span>
      <br />
      <span>
          {% if draft.registered_node %}
              <a href="{{ draft.registered_node }}">
                  {{ draft.registered_node }}
              </a>
          {% else %}
            None
          {% endif %}
      </span>
    </div>
    <div class="col-md-6 form">
      <form class="prereg-draft-form" action="{% url 'pre_reg:update_draft' draft.pk %}">
      <!-- Form -->
      {% for field in draft.form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
      {% endfor %}
    </form>
    </div>
    <div class="col-md-2">
      <br />
      <span class="btn-group form-inline">
        <fieldset {{ draft.is_pending_approval|yesno:',disabled' }}>
        <form action="{% url 'pre_reg:approve_draft' draft.pk %}" method="POST" style="display: inline">
          <input type="hidden" name="page" value="{{ page.number }}">
          <input type="submit" style="margin-right: 5px"
                 class="btn btn-warning prereg-draft-approve"
                 value="Approve"/>
        </form>
        <form action="{% url 'pre_reg:reject_draft' draft.pk %}" method="POST" style="display: inline">
          <input type="hidden" name="page" value="{{ page.number }}">
          <input type="submit"
                 class="btn btn-danger prereg-draft-reject"
                 value="Reject"/>
        </form>
        </fieldset>
      </span>
      <br />
      <br />
      <hr />
      <br />
      <span class="btn-group">
        <a style="margin-right: 5px" target="_blank"
           href="{% url 'pre_reg:view_draft' draft.pk %}" class="btn btn-default">View Draft</a>
        <button class="btn btn-primary prereg-draft-save">Save</button>
      </span>
    </div>
  </div>
  {% endfor %}
</div>
<div class="pagination pull-right">
  <span class="step-links">
    {% if page.has_previous %}
    <a class="btn btn-default" href="?page=1">first</a>
    <a class="btn btn-primary" href="?page={{ page.previous_page_number }}">previous</a>
    {% endif %}

    <span style="margin: 5px" class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>

    {% if page.has_next %}
    <a class="btn btn-primary" href="?page={{ page.next_page_number }}">next</a>
    <a class="btn btn-default" href="?page={{ page.paginator.num_pages }}">last</a>
 {% endif %}
  </span>
</div>
{% endblock %}
{% block bottom_js %}
  {% render_bundle 'prereg-admin-page' %}
{% endblock %}

admin/templates/pre_reg/registration_editor_extensions.html
<!-- OSF Upload -->
<script type="text/html" id="osf-upload">
    <span data-bind="template: {data: $data, name: format}"></span>
</script>

<script type="text/html" id="osf-upload-open">
  <div id="selectedFile">File selected for upload:
    <span id="fileName" data-bind="text: extra().selectedFileName">no file selected</span>
    <button data-bind="visible: hasSelectedFile,
                       click: unselectFile"
            style="margin-left: 5px;"
            class="btn btn-xs btn-danger fa fa-times"></button>
  </div>
  <div data-bind="attr.id: $data.id, osfUploader"></div>
</script>

<script type="text/html" id="osf-upload-toggle">
  <div id="selectedFile">File selected for upload:
    <span id="fileName" data-bind="text: extra().selectedFileName">no file selected</span>
    <button data-bind="visible: hasSelectedFile,
                       click: unselectFile"
            style="margin-left: 5px;"
            class="btn btn-xs btn-danger fa fa-times"></button>
  </div>
  <a data-bind="click: toggleUploader">Attach File</a>
  <span data-bind="visible: showUploader">
    <div data-bind="attr.id: $data.id, osfUploader"></div>
  </span>
</script>

admin/templates/pre_reg/registration_editor_templates.html
<!-- String Types -->
<script type="text/html" id="string">
  <span data-bind="template: {data: $data, name: format}"></span>
</script>

<script type="text/html" id="text">
  <input data-bind="valueUpdate: 'keyup',
                    value: value"
         type="text" class="form-control" />
</script>
<script type="text/html" id="match">
  <input data-bind="valueUpdate: 'keyup',
                    value: value,
                    attr.placeholder: match" type="text" class="form-control" />
</script>
<script type="text/html" id="textarea">
  <textarea data-bind="valueUpdate: 'keyup',
                       textInput: value"
            class="form-control"> </textarea>
</script>
<!-- Number Types -->
<script type="text/html" id="number">
  <input data-bind="valueUpdate: 'keyup',
                    value: value" type="text" class="form-control">
</script>
<!-- Enum Types -->
<script type="text/html" id="choose">
  <span data-bind="template: {data: $data, name: format}"></span>
</script>
<script type="text/html" id="singleselect">
  <div class="col-md-12" data-bind="foreach: {data: options, as: 'option'}">
    <p>
      <input type="radio" data-bind="checked: $parent.value,
                                     value: option"/>
      <span data-bind="text: option"></span>
    </p>
  </div>
</script>
<script type="text/html" id="multiselect">
  <div class="col-md-12" data-bind="foreach: {data: options, as: 'option'}">
    <p>
      <input type="checkbox" data-bind="attr.value: option,
                                        checked: $parent.value,
                                        checkedValue: option" />
      <span data-bind="text: option"></span>
    </p>
  </div>
</script>

<script type="text/html" id="object">
  <span data-bind="foreach: {data: $root.iterObject($data.properties)}">
      <div data-bind="template: {data: $root.context(value, $root), name: value.type}"></div>
      <hr />
    </span>
  </span>
</script>

<!-- Base Template -->
<script type="text/html" id="editorBase">
  <div class="well" style="padding-bottom: 0px;">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="control-label" data-bind="text: title"></label>
          <span class="text-muted" data-bind="if: required">
            (required)
          </span>
          <p class="help-block" data-bind="text: description"></p>
          <span data-bind="if: help" class="example-block">
            <a data-bind="click: toggleExample">Show Example</a>
            <p data-bind="visible: showExample, html: help"></p>
          </span>
          <br />
          <br />
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <span data-bind="with: $root.context($data, $root)">
                  <span data-bind="if: $root.showValidation">
                    <p class="text-error" data-bind="validationMessage: $data.value"></p>
                    <ul class="list-group" data-bind="foreach: $data.validationMessages">
                      <li class="list-group-item">
                        <span class="text-danger"
                              data-bind="text: $data">
                        </span>
                      </li>
                    </ul>
                  </span>
                  <div data-bind="template: {data: $data, name: type}"></div>
                  <br />
                </span>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</script>

<script type="text/html" id="editor">
  <span data-bind="if: $data.description">
    <div class="well">
      <blockquote>
        <p data-bind="html: description"></p>
      </blockquote>
    </div>
  </span>
  <div data-bind="foreach: {data: $data.questions, as: 'question'}">
    <span data-bind="template: {data: $data, name: 'editorBase'}"></span>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="well" data-bind="template: {data: $data, name: 'commentable'}"></div>
    </div>
  </div>
</script>

<!-- Commentable -->
<script type="text/html" id="commentable">
  <div class="registration-editor-comments">
    <h4> Comments </h4>
    <ul class="list-group" id="commentList" data-bind="foreach: {data: comments, as: 'comment'}">
        <li class="list-group-item">
          <div class="row" data-bind="if: comment.isDeleted">
            <div class="col-md-12">
              <strong><span data-bind="text: comment.getAuthor"></span></strong> deleted this comment on <em data-bind="text: comment.lastModified"></em>
            </div>
          </div>
          <div class="row" data-bind="ifnot: comment.isDeleted">
            <div class="col-md-12">
              <div class="row">
                <div class="col-sm-9">
                  <strong><span data-bind="text: comment.getAuthor"></span></strong> said ...
                </div>
                <div class="col-sm-3">
                  <div style="text-align: right;" class="btn-group">
                    <button data-bind="disable: comment.saved,
                                       click: comment.toggleSaved.bind(comment, $root.save.bind($root))" class="btn btn-success fa fa-save registration-editor-comment-save"></button>
                    <button data-bind="enable: comment.canEdit,
                                       click: comment.toggleSaved.bind(comment, $root.save.bind($root))" class="btn btn-info fa fa-pencil"></button>
                    <button data-bind="enable: comment.canDelete,
                                       click: comment.delete.bind(comment, $root.save.bind($root)) "
                            class="btn btn-danger fa fa-times"></button>
                  </div>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-12 form-group">
                  <textarea class="form-control"
                          style="resize: none; overflow: scroll"
                            data-bind="disable: comment.saved,
                                       value: comment.value" type="text"></textarea>
                </div>
              </div>
            </div>
          </div>
        </li>
    </ul>
    <div class="input-group">
      <input class="form-control registration-editor-comment" type="text"
             data-bind="value: currentQuestion.nextComment,
                        valueUpdate: 'keyup'" />
      <span class="input-group-btn">
        <button class="btn btn-primary"
                data-bind="click: currentQuestion.addComment.bind(currentQuestion, $root.save.bind($root)),
                           enable: currentQuestion.allowAddNext">Add</button>
      </span>
    </div>
  </div>
</script>

{% include "pre_reg/registration_editor_extensions.html" %}