admin/base/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.views.generic import RedirectView

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
    url(base_pattern,
        include(patterns('',
                         url(r'^$', views.home, name='home'),
                         url(r'^django_admin/', include(admin.site.urls)),
                         url(r'^spam/', include('admin.spam.urls', namespace='spam')),
                         url(r'^auth/', include('admin.common_auth.urls', namespace='auth')),
                         url(r'^nodes/',
                             include('admin.nodes.urls', namespace='nodes')),
                         url(r'^users/',
                             include('admin.users.urls', namespace='users')),
                         url(r'^prereg/', include('admin.pre_reg.urls', namespace='pre_reg')),
                         url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                            views.password_reset_confirm_custom, name='password_reset_confirm'),
                         url(r'^reset/done/$', views.password_reset_done,
                            name='password_reset_complete'),
                         )
                )
        ),
    url(r'^$', RedirectView.as_view(url='/admin/')),
]

admin/spam/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.SpamList.as_view(), name='spam'),
    url(r'^(?P<spam_id>[a-z0-9]+)/$', views.SpamDetail.as_view(), name='detail'),
    url(r'^(?P<spam_id>[a-z0-9]+)/email/$', views.email, name='email'),
]

api/base/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from settings import API_BASE
from website import settings as osf_settings

from . import views

base_pattern = '^{}'.format(API_BASE)

urlpatterns = [
    url(base_pattern,
        include(patterns('',
                         url(r'^$', views.root, name='root'),
                         url(r'^applications/', include('api.applications.urls', namespace='applications')),
                         url(r'^comments/', include('api.comments.urls', namespace='comments')),
                         url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                         url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                         url(r'^users/', include('api.users.urls', namespace='users')),
                         url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                         url(r'^logs/', include('api.logs.urls', namespace='logs')),
                         url(r'^files/', include('api.files.urls', namespace='files')),
                         url(r'^docs/', include('rest_framework_swagger.urls')),
                         url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                         ))
        )
]

if osf_settings.DEV_MODE:
    urlpatterns.extend([
        url(r'^v2/collections/', include('api.collections.urls', namespace='collections')),
    ])

urlpatterns += static('/static/', document_root=settings.STATIC_ROOT)

handler404 = views.error_404

api/comments/urls.py
from django.conf.urls import url
from api.comments import views

urlpatterns = [
    url(r'^(?P<comment_id>\w+)/$', views.CommentDetail.as_view(), name=views.CommentDetail.view_name),
    url(r'^(?P<comment_id>\w+)/reports/$', views.CommentReportsList.as_view(), name=views.CommentReportsList.view_name),
    url(r'^(?P<comment_id>\w+)/reports/(?P<user_id>\w+)/$', views.CommentReportDetail.as_view(), name=views.CommentReportDetail.view_name),
]

admin/spam/forms.py
from django import forms

from website.project.model import Comment


class ConfirmForm(forms.Form):
    confirm = forms.ChoiceField(
        choices=[(Comment.SPAM, 'Spam'), (Comment.HAM, 'Ham')],
        widget=forms.RadioSelect(),
    )

admin/spam/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, ListView
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse
from django.views.defaults import page_not_found

from modularodm import Q
from website.project.model import Comment

from .serializers import serialize_comment
from .forms import ConfirmForm


class SpamList(ListView):
    template_name = 'spam/spam.html'
    paginate_by = 10
    paginate_orphans = 1
    ordering = 'date_created'
    context_object_name = 'spam'

    def __init__(self):
        self.status = str(Comment.FLAGGED)
        super(SpamList, self).__init__()

    def get_queryset(self):
        self.status = self.request.GET.get('status', u'1')
        query = (
            Q('reports', 'ne', {}) &
            Q('reports', 'ne', None) &
            Q('spam_status', 'eq', int(self.status))
        )
        return Comment.find(query).sort(self.ordering)

    def get_context_data(self, **kwargs):
        queryset = kwargs.pop('object_list', self.object_list)
        page_size = self.get_paginate_by(queryset)
        paginator, page, queryset, is_paginated = self.paginate_queryset(
            queryset, page_size)
        context = {
            'spam': map(serialize_comment, queryset),
            'page': page,
            'status': self.status,
            'page_number': page.number
        }
        return super(SpamList, self).get_context_data(**context)


class SpamDetail(FormView):
    form_class = ConfirmForm
    template_name = 'spam/comment.html'

    def __init__(self):
        self.spam_id = None
        self.page = 1
        self.item = None
        super(SpamDetail, self).__init__()

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        try:
            return super(SpamDetail, self).get(request, *args, **kwargs)
        except AttributeError:
            return page_not_found(request)  # TODO: 1.9 update to have exception with node/user 404.html will be added

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        try:
            self.get_context_data(**kwargs)
        except AttributeError:
            return page_not_found(request)  # TODO: 1.9 update to have exception
        return super(SpamDetail, self).post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.spam_id = self.kwargs['spam_id']
        self.item = Comment.load(self.spam_id)
        self.page = self.request.GET.get('page', 1)
        kwargs = super(SpamDetail, self).get_context_data(**kwargs)
        kwargs.setdefault('page_number', self.page)
        kwargs.setdefault('comment', serialize_comment(self.item))
        return kwargs

    def form_valid(self, form):
        if int(form.cleaned_data.get('confirm')) == Comment.SPAM:
            self.item.confirm_spam(save=True)
        else:
            self.item.confirm_ham(save=True)
        return super(SpamDetail, self).form_valid(form)

    @property
    def success_url(self):
        return '{}?page={}'.format(
            reverse('spam:detail', kwargs={'spam_id': self.spam_id}),
            self.page
        )


@login_required
def email(request, spam_id):
    context = {
        'comment': serialize_comment(Comment.load(spam_id), full=True),
        'page_number': request.GET.get('page', 1),
    }
    return render(request, 'spam/email.html', context)

api/comments/views.py
import requests

from rest_framework import generics, permissions as drf_permissions
from rest_framework.exceptions import NotFound, ValidationError, PermissionDenied
from rest_framework.status import is_server_error

from modularodm import Q
from modularodm.exceptions import NoResultsFound

from api.base.exceptions import Gone, ServiceUnavailableError
from api.base import permissions as base_permissions
from api.base.views import JSONAPIBaseView
from api.comments.permissions import (
    CommentDetailPermissions,
    CommentReportsPermissions
)
from api.comments.serializers import (
    CommentSerializer,
    CommentDetailSerializer,
    CommentReportSerializer,
    CommentReportDetailSerializer,
    CommentReport
)
from framework.auth.core import Auth
from framework.auth.oauth_scopes import CoreScopes
from framework.exceptions import PermissionsError
from website.project.model import Comment
from website.files.models import StoredFileNode, TrashedFileNode
from website.files.models.dropbox import DropboxFile
from website.util import waterbutler_api_url_for


class CommentMixin(object):
    """Mixin with convenience methods for retrieving the current comment  based on the
    current URL. By default, fetches the comment based on the comment_id kwarg.
    """

    serializer_class = CommentSerializer
    comment_lookup_url_kwarg = 'comment_id'

    def get_comment(self, check_permissions=True):
        pk = self.kwargs[self.comment_lookup_url_kwarg]
        try:
            comment = Comment.find_one(Q('_id', 'eq', pk) & Q('root_target', 'ne', None))
        except NoResultsFound:
            raise NotFound

        # Deleted root targets still appear as tuples in the database and are included in
        # the above query, requiring an additional check
        if isinstance(comment.root_target.referent, TrashedFileNode):
            comment.root_target = None
            comment.save()

        if comment.root_target is None:
            raise NotFound

        if isinstance(comment.root_target.referent, StoredFileNode):
            root_target = comment.root_target
            referent = root_target.referent

            if referent.provider == 'osfstorage':
                try:
                    StoredFileNode.find(
                        Q('node', 'eq', comment.node._id) &
                        Q('_id', 'eq', referent._id) &
                        Q('is_file', 'eq', True)
                    )
                except NoResultsFound:
                    Comment.update(Q('root_target', 'eq', root_target), data={'root_target': None})
                    del comment.node.commented_files[root_target._id]
                    raise NotFound
            else:
                if referent.provider == 'dropbox':
                    referent = DropboxFile.load(referent._id)
                url = waterbutler_api_url_for(comment.node._id, referent.provider, referent.path, meta=True)
                waterbutler_request = requests.get(
                    url,
                    cookies=self.request.COOKIES,
                    headers={'Authorization': self.request.META.get('HTTP_AUTHORIZATION')},
                )

                if waterbutler_request.status_code == 401:
                    raise PermissionDenied

                if waterbutler_request.status_code == 404:
                    Comment.update(Q('root_target', 'eq', root_target), data={'root_target': None})
                    raise NotFound

                if is_server_error(waterbutler_request.status_code):
                    raise ServiceUnavailableError(detail='Could not retrieve files information at this time.')

                try:
                    waterbutler_request.json()['data']
                except KeyError:
                    raise ServiceUnavailableError(detail='Could not retrieve files information at this time.')

        if check_permissions:
            # May raise a permission denied
            self.check_object_permissions(self.request, comment)
        return comment


class CommentDetail(JSONAPIBaseView, generics.RetrieveUpdateDestroyAPIView, CommentMixin):
    """Details about a specific comment. *Writeable*.

    ###Permissions

    Comments on public nodes are given read-only access to everyone. Comments on private nodes are only visible
    to contributors and administrators on the parent node. Only the user who created the comment has permission
    to edit and delete the comment.

    Note that if an anonymous view_only key is being used, the user relationship will not be exposed.

    ##Attributes

    OSF comment entities have the "comments" `type`.

        name           type               description
        ---------------------------------------------------------------------------------
        content        string             content of the comment
        date_created   iso8601 timestamp  timestamp that the comment was created
        date_modified  iso8601 timestamp  timestamp when the comment was last updated
        modified       boolean            has this comment been edited?
        deleted        boolean            is this comment deleted?
        is_abuse       boolean            has this comment been reported by the current user?
        has_children   boolean            does this comment have replies?
        can_edit       boolean            can the current user edit this comment?

    ##Relationships

    ###User

    The user who created the comment.

    ###Node

    The project associated with this comment.

    ###Target

    The "parent" of the comment. If the comment was made on a node, the target is the node. If the comment
    is a reply, its target is the comment it was in reply to.

    ###Replies
    List of replies to this comment. New replies can be created through this endpoint.

    ###Reports
    List of spam reports for this comment. Only users with permission to create comments can
    access this endpoint, and users can only see reports that they have created.

    ##Links

        self:  the canonical api endpoint of this comment

    ##Actions

    ###Update

        Method:        PUT / PATCH
        URL:           /links/self
        Query Params:  <none>
        Body (JSON):   {
                         "data": {
                           "type": "comments",   # required
                           "id":   {comment_id}, # required
                           "attributes": {
                             "content":       {content},        # mandatory
                             "deleted":       {is_deleted},     # mandatory
                           }
                         }
                       }
        Success:       200 OK + comment representation

    To update a comment, issue either a PUT or a PATCH request against the `/links/self` URL.  The `content`
    and `deleted` fields are mandatory if you PUT and optional if you PATCH. Non-string values will be accepted and
    stringified, but we make no promises about the stringification output.  So don't do that.

    To restore a deleted comment, issue a PATCH request against the `/links/self` URL, with `deleted: False`.

    ###Delete

        Method:        DELETE
        URL:           /links/self
        Query Params:  <none>
        Success:       204 No Content

    To delete a comment send a DELETE request to the `/links/self` URL.  Nothing will be returned in the response
    body. Attempting to delete an already deleted comment will result in a 400 Bad Request response.

    ##Query Params

    *None*.

    #This Request/Response

    """
    permission_classes = (
        drf_permissions.IsAuthenticatedOrReadOnly,
        CommentDetailPermissions,
        base_permissions.TokenHasScope,
    )

    required_read_scopes = [CoreScopes.NODE_COMMENTS_READ]
    required_write_scopes = [CoreScopes.NODE_COMMENTS_WRITE]

    serializer_class = CommentDetailSerializer
    view_category = 'comments'
    view_name = 'comment-detail'

    # overrides RetrieveAPIView
    def get_object(self):
        return self.get_comment()

    def perform_destroy(self, instance):
        auth = Auth(self.request.user)
        if instance.is_deleted:
            raise ValidationError('Comment already deleted.')
        else:
            try:
                instance.delete(auth, save=True)
            except PermissionsError:
                raise PermissionDenied('Not authorized to delete this comment.')


class CommentReportsList(JSONAPIBaseView, generics.ListCreateAPIView, CommentMixin):
    """List of reports made for a comment. *Writeable*.

    Paginated list of reports for a comment. Each resource contains the full representation of the
    report, meaning additional requests to an individual comment's report detail view are not necessary.

    ###Permissions

    The comment reports endpoint can only be viewed by users with permission to comment on the node. Users
    are only shown comment reports that they have made.

    ##Attributes

    OSF comment report entities have the "comment_reports" `type`.

        name           type               description
        -------------------------------------------------------------------------------------
        category        string            the type of spam, must be one of the allowed values
        message         string            description of why the comment was reported

    ##Links

    See the [JSON-API spec regarding pagination](http://jsonapi.org/format/1.0/#fetching-pagination).

    ##Actions

    ###Create

        Method:        POST
        URL:           /links/self
        Query Params:  <none>
        Body (JSON):   {
                         "data": {
                           "type": "comment_reports",      # required
                           "attributes": {
                             "category":       {category}, # mandatory
                             "message":        {text},     # optional
                           }

admin/templates/spam/comment.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>Comment</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <a href="{% url 'spam:spam' %}?page={{ page_number }}"
               class="btn btn-primary">
                Back to list
            </a>
            <a href="{% url 'spam:email' comment.id %}?page={{ page_number }}"
               class="btn btn-default">
                Email
            </a>
        </div>

        <br>

        <div class="row">
        <div class="panel col-md-6">
        <form action="{% url 'spam:detail' comment.id %}?page={{ page_number }}"
              method="post" class="form-inline">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">{{ form.errors }}</div>
            {% endif %}
            <label for="{{ form.confirm.id_for_label }}">Confirm:</label>
            <div class="btn-group" data-toggle="buttons">
                {% for choice in form.confirm  %}
                    {{ choice.id }}
                <label class="btn btn-primary">
                    <input type="radio" id="{{ choice.id_for_label }}" autocomplete="off">{{ choice.choice_label }}{{ choice.tag }}
                </label>
                {% endfor %}
            </div>
            <input class="btn btn-danger" type="submit" value="Submit">
        </form>
        </div>
        </div>

        {# General info about the comment #}
        <div class="row">
            <div class="col-md-6">
                <h4>
                    <strong>Author:</strong> {{ comment.author.fullname }}
                    <small>
                        (<a href="{{ comment.author_path }}">
                            User's osf profile
                        </a>)
                    </small>
                </h4>
            </div>
            <div class="col-md-6">
                <h4><strong>Comment ID:</strong> {{ comment.id }}</h4>
            </div>
        </div>

        {# Spam Status #}
        <div class="row">
            <div class="col-md-6">
                <h4>
                    <strong>Status: </strong>
                    {% if comment.spam_status == 0 %}
                        <span class="label label-default">Unknown</span>
                    {% elif comment.spam_status == 1 %}
                        <span class="label label-warning">Flagged</span>
                    {% elif comment.spam_status == 2 %}
                        <span class="label label-danger">Spam</span>
                    {% elif comment.spam_status == 4 %}
                        <span class="label label-success">Ham</span>
                    {% endif %}
                </h4>
            </div>
        </div>

        {# Comment date and content #}
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>
                        <strong>Comment content</strong>
                        created on:
                        {{ comment.date_created }}
                    </h4>
                </div>
                <div class="panel-body">
                    {{ comment.content }}
                </div>
            </div>
        </div>

        <h4><strong>Reports</strong></h4>
        {% for report in comment.reports %}
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>
                            Type:
                            <strong>
                                {{ report.category }}
                            </strong>
                        </h4>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-6">
                            <strong>Reporter:</strong>
                            {{ report.reporter.fullname }}
                        </div>
                        <div class="col-md-6">
                            <strong>
                                Reason:
                            </strong>
                            {{ report.reason|default:"--Nothing--" }}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div>No reports!</div>
        {% endfor %}
    </div>

{% endblock content %}

admin/templates/spam/email.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>Email</title>
{% endblock title %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="btn-group col-sm-12">
                <a href="{% url 'spam:spam' %}?page={{ page_number }}"
                   class="btn btn-primary">
                    Back to list
                </a>
                <a href="{% url 'spam:detail' comment.id %}?page={{ page_number }}"
                   class="btn btn-default">
                    Back to detail
                </a>
            </div>
        </div>

        <hr>

        <div class="row">
            <form>
                <div class="form-group">
                <label for="author">
                    <strong>Author:</strong>
                </label>
                <input id="author"
                       placeholder="{{ comment.author.fullname }}"
                       disabled>
                </div>

                <div class="form-group">
                <label for="email">
                    <strong>Email:</strong>
                </label>
                <select id="email">
                    {% for email in comment.author.emails %}
                        {% if forloop.counter0 == 0 %}
                            <option value="{{ email }}" selected>
                                {{ email }}
                            </option>
                        {% else %}
                            <option value="{{ email }}">
                                {{ email }}
                            </option>
                        {% endif %}
                    {% endfor %}
                </select>
                <p class="help-block">User's primary email originally selected</p>
                </div>

                <label for="message">
                    <strong>Message</strong>
                </label>
                <div class="form-group">
                    <textarea id="message" rows="10" cols="80">
Dear {{ comment.author.fullname }},

Your comment on the OSF was flagged as spam. We would like to moderate a solution and believe your input would be helpful.

Context:
"{{ comment.content }}"

Sincerely,
The folks at COS
                    </textarea>
                </div>
                <button type="submit" class="btn btn-primary">
                    Submit
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

admin/templates/spam/spam.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}

{% load static %}
{% block title %}
    <title>List of Spam</title>
{% endblock title %}
{% block content %}
    <h2>List of Spam</h2>
    <div class="btn-group">
    {% if status == '1' %}
        <a href="{% url 'spam:spam' %}?status=1&page={{ page_number }}"
           class="btn btn-primary active disabled">Flagged</a>
    {% else %}
        <a href="{% url 'spam:spam' %}?status=1&page={{ page_number }}"
           class="btn btn-primary">Flagged</a>
    {% endif %}
    {% if status == '2' %}
        <a href="{% url 'spam:spam' %}?status=2&page={{ page_number }}"
           class="btn btn-primary active disabled">Spam</a>
    {% else %}
        <a href="{% url 'spam:spam' %}?status=2&page={{ page_number }}"
           class="btn btn-primary">Spam</a>
    {% endif %}
    {% if status == '4' %}
        <a href="{% url 'spam:spam' %}?status=4&page={{ page_number }}"
           class="btn btn-primary active disabled">Ham</a>
    {% else %}
        <a href="{% url 'spam:spam' %}?status=4&page={{ page_number }}"
           class="btn btn-primary">Ham</a>
    {% endif %}
    </div>
    {% include "util/pagination.html" with items=page status=status %}
    <table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th><label for="all"></label>
                <input id="all" type="checkbox" disabled>
            </th>
            <th>Author</th>
            <th>Reporter</th>
            <th>Date</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody>
    {% for comment in spam %}
    <tr>
        <td>
            <label for="{{ comment.id }}"></label>
            <input id="{{ comment.id }}" type="checkbox" disabled>
        </td>
        <td>
            {{ comment.author.fullname }}
        </td>
        <td>
            {% with comment.reports|first as first_report %}
                {{ first_report.reporter.fullname }}
            {% endwith %}
        </td>
        <td>
            {{ comment.date_created|date }}
        </td>
        <td>
            {{ comment.content|truncatechars:30 }}
        </td>
        <td>
            <a href="{% url 'spam:detail' comment.id %}?page={{ page_number }}"
               class="btn btn-primary">
                Detail
            </a>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td>No more Spam!</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock content %}