admin/base/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.views.generic import RedirectView

from settings import ADMIN_BASE

from . import views

base_pattern = '^{}'.format(ADMIN_BASE)

urlpatterns = [
    ### ADMIN ###
    url(r'^project/', include('admin.pre_reg.urls', namespace='pre_reg')),
    url(base_pattern,
        include(patterns('',
                         url(r'^$', views.home, name='home'),
                         url(r'^django_admin/', include(admin.site.urls)),
                         url(r'^spam/', include('admin.spam.urls', namespace='spam')),
                         url(r'^auth/', include('admin.common_auth.urls', namespace='auth')),
                         url(r'^nodes/',
                             include('admin.nodes.urls', namespace='nodes')),
                         url(r'^users/',
                             include('admin.users.urls', namespace='users')),
                         url(r'^prereg/', include('admin.pre_reg.urls', namespace='pre_reg')),
                         url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                            views.password_reset_confirm_custom, name='password_reset_confirm'),
                         url(r'^reset/done/$', views.password_reset_done,
                            name='password_reset_complete'),
                         )
                )
        ),
    url(r'^$', RedirectView.as_view(url='/admin/')),
]

admin/nodes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.NodeFormView.as_view(), name='node'),
]

admin/pre_reg/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.prereg, name='prereg'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/$', views.view_draft, name='view_draft'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/update/$', views.update_draft, name='update_draft'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/approve/$', views.approve_draft, name='approve_draft'),
    url(r'^drafts/(?P<draft_pk>[0-9a-z]+)/reject/$', views.reject_draft, name='reject_draft'),
    url(r'^(?P<node_id>[a-zA-Z0-9]{5})/files/(?P<provider>.+?)/(?P<file_id>.+)/?', views.view_file, name='view_file')
]

admin/spam/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.SpamList.as_view(), name='spam'),
    url(r'^(?P<spam_id>[a-z0-9]+)/$', views.SpamDetail.as_view(), name='detail'),
    url(r'^(?P<spam_id>[a-z0-9]+)/email/$', views.email, name='email'),
]

admin/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='user'),
]

api/base/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from settings import API_BASE
from website import settings as osf_settings

from . import views

base_pattern = '^{}'.format(API_BASE)

urlpatterns = [
    url(base_pattern,
        include(patterns('',
                         url(r'^$', views.root, name='root'),
                         url(r'^applications/', include('api.applications.urls', namespace='applications')),
                         url(r'^comments/', include('api.comments.urls', namespace='comments')),
                         url(r'^nodes/', include('api.nodes.urls', namespace='nodes')),
                         url(r'^registrations/', include('api.registrations.urls', namespace='registrations')),
                         url(r'^users/', include('api.users.urls', namespace='users')),
                         url(r'^tokens/', include('api.tokens.urls', namespace='tokens')),
                         url(r'^logs/', include('api.logs.urls', namespace='logs')),
                         url(r'^files/', include('api.files.urls', namespace='files')),
                         url(r'^docs/', include('rest_framework_swagger.urls')),
                         url(r'^institutions/', include('api.institutions.urls', namespace='institutions')),
                         ))
        )
]

if osf_settings.DEV_MODE:
    urlpatterns.extend([
        url(r'^v2/collections/', include('api.collections.urls', namespace='collections')),
    ])

urlpatterns += static('/static/', document_root=settings.STATIC_ROOT)

handler404 = views.error_404

admin/base/forms.py
from django import forms


class GuidForm(forms.Form):
    guid = forms.CharField(label='Guid', max_length=5, required=True)

admin/base/views.py
from django.contrib import messages
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.http import urlsafe_base64_decode
from django.views.generic import FormView
from django.views.defaults import page_not_found

from admin.common_auth.models import MyUser
from admin.base.forms import GuidForm


@login_required
def home(request):
    context = {}
    return render(request, 'home.html', context)


def password_reset_done(request, **kwargs):
    messages.success(request, 'You have successfully reset your password and activated your admin account. Thank you')
    return redirect('auth:login')


def password_reset_confirm_custom(request, **kwargs):
    response = views.password_reset_confirm(request, **kwargs)
    # i.e. if the user successfully resets their password
    if response.status_code == 302:
        try:
            uid = urlsafe_base64_decode(kwargs['uidb64'])
            user = MyUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
            pass
        else:
            user.confirmed = True
            user.save()
    return response


class GuidFormView(FormView):
    form_class = GuidForm
    template_name = None
    object_type = None

    def get_guid_object(self):
        raise NotImplementedError

    def __init__(self):
        self.guid = None
        super(GuidFormView, self).__init__()

    def get(self, request, *args, **kwargs):
        try:
            return super(GuidFormView, self).get(request, args, kwargs)
        except AttributeError:
            return page_not_found(self.request)

    def get_context_data(self, **kwargs):
        self.guid = self.request.GET.get('guid', None)
        guid_object = None
        if self.guid is not None:
            try:
                guid_object = self.get_guid_object()
            except AttributeError:
                raise
        kwargs.setdefault('view', self)
        kwargs.setdefault('form', self.get_form())
        kwargs.setdefault('guid_object', guid_object)
        return kwargs

    def form_valid(self, form):
        self.guid = form.cleaned_data.get('guid').strip()
        return super(GuidFormView, self).form_valid(form)

    @property
    def success_url(self):
        raise NotImplementedError

api/base/views.py
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import generics
from rest_framework.mixins import ListModelMixin

from api.users.serializers import UserSerializer

from website import settings
from django.conf import settings as django_settings
from .utils import absolute_reverse, is_truthy

from .requests import EmbeddedRequest


class JSONAPIBaseView(generics.GenericAPIView):

    def __init__(self, **kwargs):
        assert getattr(self, 'view_name', None), 'Must specify view_name on view.'
        assert getattr(self, 'view_category', None), 'Must specify view_category on view.'
        self.view_fqn = ':'.join([self.view_category, self.view_name])
        super(JSONAPIBaseView, self).__init__(**kwargs)

    def _get_embed_partial(self, field_name, field):
        """Create a partial function to fetch the values of an embedded field. A basic
        example is to include a Node's children in a single response.

        :param str field_name: Name of field of the view's serializer_class to load
        results for
        :return function object -> dict:
        """
        if getattr(field, 'field', None):
                field = field.field
        def partial(item):
            # resolve must be implemented on the field
            view, view_args, view_kwargs = field.resolve(item)
            if issubclass(view.cls, ListModelMixin) and field.always_embed:
                raise Exception("Cannot auto-embed a list view.")
            request = EmbeddedRequest(self.request)
            view_kwargs.update({
                'request': request,
                'is_embedded': True
            })
            response = view(*view_args, **view_kwargs)
            return response.data
        return partial

    def get_serializer_context(self):
        """Inject request into the serializer context. Additionally, inject partial functions
        (request, object -> embed items) if the query string contains embeds.  Allows
         multiple levels of nesting.
        """
        context = super(JSONAPIBaseView, self).get_serializer_context()
        if self.kwargs.get('is_embedded'):
            embeds = []
        else:
            embeds = self.request.query_params.getlist('embed')

        fields = self.serializer_class._declared_fields
        fields_check = fields.copy()

        for field in fields_check:
            if getattr(fields_check[field], 'field', None):
                fields_check[field] = fields_check[field].field

        for field in fields_check:
            if getattr(fields_check[field], 'always_embed', False) and field not in embeds:
                embeds.append(unicode(field))
            if getattr(fields_check[field], 'never_embed', False) and field in embeds:
                embeds.remove(field)
        embeds_partials = {}
        for embed in embeds:
            embed_field = fields_check.get(embed)
            embeds_partials[embed] = self._get_embed_partial(embed, embed_field)

        context.update({
            'enable_esi': (
                is_truthy(self.request.query_params.get('esi', django_settings.ENABLE_ESI)) and
                self.request.accepted_media_type in django_settings.ESI_MEDIA_TYPES
            ),
            'embed': embeds_partials,
            'envelope': self.request.query_params.get('envelope', 'data'),
        })
        return context

@api_view(('GET',))
def root(request, format=None):
    """Welcome to the V2 Open Science Framework API. With this API you can access users, projects, components, logs, and files
    from the [Open Science Framework](https://osf.io/). The Open Science Framework (OSF) is a free, open-source service
    maintained by the [Center for Open Science](http://cos.io/).

    The OSF serves as a repository and archive for study designs, materials, data, manuscripts, or anything else
    associated with your research during the research process. Every project and file on the OSF has a permanent unique
    identifier, and every registration (a permanent, time-stamped version of your projects and files) can be assigned a
    DOI/ARK. You can use the OSF to measure your impact by monitoring the traffic to projects and files you make
    public. With the OSF you have full control of what parts of your research are public and what remains private.

    Beta notice: This API is currently a beta service.  You are encouraged to use the API and will receive support
    when doing so, however, while the API remains in beta status, it may change without notice as a result of
    product updates. The temporary beta status of the API will remain in place while it matures. In a future
    release, the beta status will be removed, at which point we will provide details on how long we will support
    the API V2 and under what circumstances it might change.

    #General API Usage

    The OSF API generally conforms to the [JSON-API v1.0 spec](http://jsonapi.org/format/1.0/).  Where exceptions
    exist, they will be noted.  Each endpoint will have its own documentation, but there are some general principles.

    ##Requests

    ###Canonical URLs

    All canonical URLs have trailing slashes.  A request to an endpoint without a trailing slash will result in a 301
    redirect to the canonical URL.  There are some exceptions when working with the Files API, so if a URL in a response
    does not have a slash, do not append one.

    ###Plurals

    Endpoints are always pluralized.  `/users/`, not `/user/`, `/nodes/`, not `/node/`.

    ###Common Actions

    Every endpoint in the OSF API responds to `GET`, `HEAD`, and `OPTION` requests.  You must have adequate permissions
    to interact with the endpoint.  Unauthorized use will result in 401 Unauthorized or 403 Forbidden responses.  Use
    `HEAD` to probe an endpoint and make sure your headers are well-formed.  `GET` will return a representation of the
    entity or entity collection referenced by the endpoint.  An `OPTIONS` request will return a JSON object that describes the
    endpoint, including the name, a description, the acceptable request formats, the allowed response formats, and any
    actions available via the endpoint.

    ###Filtering

    Entity collections can be filtered by adding a query parameter in the form:

        filter[<fieldname>]=<matching information>

    String queries are filtered using substring matching. For example, if you were trying to find [Lise
    Meitner](http://en.wikipedia.org/wiki/Lise_Meitner):

        /users/?filter[full_name]=meitn

    You can filter on multiple fields, or the same field in different ways, by &-ing the query parameters together.

        /users/?filter[full_name]=lise&filter[family_name]=mei

    Boolean fields should be queried with `true` or `false`.

        /nodes/?filter[registered]=true

    You can request multiple resources by filtering on id and placing comma-separated values in your query parameter.

        /nodes/?filter[id]=aegu6,me23a

    You can filter with case-sensitivity or case-insensitivity by using `contains` and `icontains`, respectively.

        /nodes/?filter[tags][icontains]=help

    ###Embedding

    All related resources that appear in the `relationships` attribute are embeddable, meaning that
    by adding a query parameter like:

        /nodes/?embed=contributors

    it is possible to fetch a Node and its contributors in a single request. The embedded results will have the following
    structure:

        {relationship_name}: {full_embedded_response}

    Where `full_embedded_response` means the full API response resulting from a GET request to the `href` link of the
    corresponding related resource. This means if there are no errors in processing the embedded request the response will have
    the format:

        data: {response}

    And if there are errors processing the embedded request the response will have the format:

        errors: {errors}

    Multiple embeds can be achieved with multiple query parameters separated by "&".

        /nodes/?embed=contributors&embed=comments

    Some endpoints are automatically embedded.

    ###Pagination

    All entity collection endpoints respond to the `page` query parameter behavior as described in the [JSON-API
    pagination spec](http://jsonapi.org/format/1.0/#crud).  However, pagination links are provided in the response, and
    you are encouraged to use that rather than adding query parameters by hand.

    ###Formatting POST/PUT/PATCH request bodies

    The OSF API follows the JSON-API spec for [create and update requests](http://jsonapi.org/format/1.0/#crud).  This means
    all request bodies must be wrapped with some metadata.  Each request body must be an object with a `data` key
    containing at least a `type` member.  The value of the `type` member must agree with the `type` of the entities
    represented by the endpoint.  If not, a 409 Conflict will be returned.  The request should also contain an
    `attributes` member with an object containing the key-value pairs to be created/updated.  PUT/PATCH requests must
    also have an `id` key that matches the id part of the endpoint.  If the `id` key does not match the id path part, a
    409 Conflict error will be returned.

    ####Example 1: Creating a Node via POST

        POST /v2/nodes/
        {
          "data": {
            "type": "nodes",
            "attributes": {
              "title" : "A Phylogenetic Tree of Famous Internet Cats",
              "category" : "project",
              "description" : "How closely related are Grumpy Cat and C.H. Cheezburger? Is memefulness inheritable?"
            }
          }
        }

    ####Example 2: Updating a User via PUT

        PUT /v2/users/me/
        {
          "data": {
            "id": "3rqxc",
            "type": "users",
            "attributes": {
              "full_name" : "Henrietta Swan Leavitt",

admin/templates/base.html
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    {% block title %}
      <title>OSF Admin | Dashboard</title>
    {% endblock %}

    <!-- Tell the browser to be responsive to screen width -->
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap -->
    <link href="{% static 'vendor/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'vendor/bower_components/admin-lte/dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- AdminLTE Skins. -->
    <link href="{% static 'vendor/bower_components/admin-lte/dist/css/skins/skin-blue.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'vendor/bower_components/raven-js/dist/raven.min.js' %}"></script>
    <script src="{% static 'vendor/bower_components/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'vendor/bower_components/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>

    {% block top_includes %}

    {% endblock %}
  </head>
  <body class="skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      {% block header %}
      <header class="main-header">

        <!-- Logo -->
        <a href="{% url 'home' %}" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>O</b>SF</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>OSF</b>Admin</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="hidden-xs">Logged in as {{ request.user.get_username }}</span>
                </a>
              </li>
              <li>
                <a href="{% url 'auth:logout' %}" class="btn btn-danger btn-flat">Sign out</a>
              </li>
            </ul>
          </div>
        </nav>
        {% endblock %}
      </header>
      {% block sidebar %}
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>
            <li><a href="{% url 'nodes:node' %}"><i class='fa fa-link'></i><span> OSF Nodes</span> </a></li>
            <li><a href="{% url 'users:user' %}"><i class='fa fa-link'></i> <span>OSF Users</span></a></li>
            <li><a href="{% url 'spam:spam' %}"><i class='fa fa-link'></i> <span>OSF Spam</span></a></li>
            {% if 'prereg_group' in request.user.group_names %}
            <li><a href="{% url 'pre_reg:prereg' %}"><i class='fa fa-link'></i> <span>OSF Prereg</span></a></li>
            {% endif %}
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>
      {% endblock %}
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
        <section class="content">
          {% block content %}
          <h1>
           Welcome to the OSF Admin Home Page
          </h1>
          <!-- Your Page Content Here -->
          {% endblock %}
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- Default to the left -->
        <strong>Copyright &copy; 2015-2016 <a href="http://www.osf.io">osf.io</a>.</strong> All rights reserved.
      </footer>

    </div><!-- ./wrapper -->

    <!-- Included JS -->
    {% render_bundle 'vendor' %}
    {% render_bundle 'admin-base-page' %}

    {% block bottom_js %}

    {% endblock %}

  </body>
</html>

admin/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1> Hello {{ user.get_username }}, </h1>
  <section class="content">
    <h3>Welcome to the OSF Admin Home Page</h3>
    <p> Use the menu on the left to access admin pages. </p>
  </section>
{% endblock %}

admin/templates/login.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}


{% block title %}
<title>OSFAdmin | Log in</title>
{% endblock %}

{% block top_includes %}
  {% render_bundle 'vendor' %}
{% endblock %}

{% block content %}
  <!-- hide navbar and sidebar -->
  {% block navbar %}
  {% endblock %}
  {% block sidebar %}
  {% endblock %}

  <div class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <b>OSF</b>Admin</a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form action="" method="post">
          {% csrf_token %}
          {% if form.non_field_errors %} <span class="text-danger"> {{ form.non_field_errors | striptags }} </span> {% endif %}
          <div class="form-group">
            <label for="username">Email:</label>
            <p>{{ form.email }}</p>
            {% if form.email.errors %}<span class="text-danger"> {{ form.email.errors }}</span>{% endif %}
          </div>
          <div class="form-group">
            <label for="username">Password:</label>
            <p>{{ form.password }}</p>
            {% if form.password.errors %}<span class="text-danger"> {{ form.password.errors }}</span>{% endif %}
          </div>
          <div class="row">
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
          </div>
          <div>
            {% if messages %} <!-- TODO: refactor message code to display proper class type -->
            <ul>
              {% for message in messages %}
              {% if message.level == 40 %}
                <li class="text-danger">
                {% else %}
                <li class="text-success">
                {% endif %}
                {{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>
        </form>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
    <!-- Bootstrap 3.3.2 JS -->
    {% render_bundle 'vendor' %}
    <!-- AdminLTE App -->
    {% render_bundle 'admin-base-page' %}
  </div>
{% endblock %}